### PR TITLE
Add version to API

### PR DESCRIPTION
**Pull request by pontusmelke**
Moved `neo4j` to `neo4j.v1` in order to facilitate API migrations in
future versions.

### CODE REVIEW

**Comment by jakewins** [comment]
IMO, we should keep the `neo4j` root namespace, and introduce a `v1` namespace inside it instead:

    require('neo4j.v1');
    import 'neo4j.v1';

**Comment by jakewins** [comment]
This should be possible by adding a `v1` folder inside the src dir, and exposing that `v1` folder though the `neo4j.js` file exports.

**Comment by pontusmelke** [comment]
@jakewins any better, I think it is `require('neo4j').v1;` but otherwise I think it is what you meant?

**Comment by jakewins** [comment]
+1

**Pull request merged**
