### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by deemeetree**
Multiple transactions example — I think it's important to show how multiple transactions can be submitted before the final commit.

### CODE REVIEW

**Comment by lutovich** [comment]
Hi @deemeetree,

Thanks for this PR!

To be able to merge your changes we will need a signed CLA from you. See http://neo4j.com/developer/cla/ for further information. Additional information on contributing code is found at http://neo4j.com/developer/contributing-code/.

**Comment by lutovich** [comment]
Hi @deemeetree, could you please sign the CLA?

**Comment by deemeetree** [comment]
Hello Konstantin

I signed it and sent it to to cla@neo4jtechnology.com so you can merge the #333

Thanks!

Dmitry

**Comment by lutovich** [comment]
PR now merged. Thanks @deemeetree.

**Pull request merged**
