### PR TITLE
[#315] Fixes PathSegment constructor

### PR DESCRIPTION
**Pull request by slapersonne**
- Fixes `rel` property name in setter of constructor

### CODE REVIEW

**Comment by lutovich** [comment]
Hi @slapersonne,

Thanks a lot for reporting this!

I think this issue should instead be fixed in TypeScript declaration file here https://github.com/neo4j/neo4j-javascript-driver/blob/1.6/types/v1/graph-types.d.ts#L66. Otherwise backwards compatibility will break when problem is fixed in JS source. Could you please change this PR to fix TS declaration instead?

To be able to merge your changes we will need a signed CLA from you.
See http://neo4j.com/developer/cla/ for further information.
Additional information on contributing code is found at
http://neo4j.com/developer/contributing-code/

**Comment by slapersonne** [comment]
Thank you for your quick answer @lutovich.
I updated this PR accordingly and agreed the CLA.
Please feel free to let me know if something else is missing.

**Comment by lutovich** [comment]
@slapersonne changes look good to me and we've received the CLA. Thanks!

Could you please squash all commits in one and use the same git account as connected to your github? Our contributor verification is going a bit crazy because of last two commits. Build is red because of this. Sorry.

**Comment by slapersonne** [comment]
@lutovich No problem, that should be correct now.
Do not hesitate to tell me is something else is bad or missing.

**Comment by lutovich** [comment]
Thanks for the fix @slapersonne!
PR now merged and commit cherry-picked to 1.5 branch with https://github.com/neo4j/neo4j-javascript-driver/commit/47f587583cc1386a4b597153ab30de2e85cd125c.

**Pull request merged**
