### PR TITLE
update configuration file

### PR DESCRIPTION
**Pull request by whatSocks**
Is this correct?

### CODE REVIEW

**Comment by zhenlineo** [comment]
I personally do not think it is needed to add this part as Bolt is enabled by default in 3.0+ Neo4j databases. For previous versions, no Bolt is supported at all. What do you think?

**Comment by whatSocks** [comment]
@zhenlineo I recently downloaded Neo4j 3.0.3 (Mac .dmg) and it was not enabled, as I found out when I tried to use Bolt.

I'll re-download and see.

**Comment by technige** [comment]
This sounds like a possible packaging bug.

cc: @benbc

**Comment by whatSocks** [comment]
neo4j-import doesn't work either with this version, but I guess that's a separate issue.

**Comment by technige** [comment]
Do you get an error with `neo4j-import`?

**Comment by whatSocks** [comment]
@nigelsmall only with neo4j-desktop, but I suppose that's a feature not a bug :(

**Comment by technige** [comment]
@whatSocks I'm not sure I follow. Either way, if you have a `neo4j-import` or `neo4j-desktop` related bug, it'll be best to share it on the relevant repo so it pops up in front of the best people to solve it.

**Comment by zhenlineo** [comment]
@whatSocks Hi, I have reported the problem where bolt is not enabled by default in mac installer. Hopefully it will be fixed soon. Regarding your problem for neo4j-import, if you still have the problem, you are most welcome to raise an issue it our neo4j/neo4j the main repo.

I am closing this PR as it is not a fix that should go into driver but server side. Still thanks so much for issuing the PR. You are most welcome to give us more PRs.

Cheers,
Zhen

**Pull request closed without merging**
