### PR TITLE
Add type assertion to is functions

### PR DESCRIPTION
**Pull request by thebestnom**
Allow for easier use in typescript of is function

### CODE REVIEW

**Review by bigmontz — COMMENTED** [review]
Thanks for the contribution. 

It doesn't see to have harm in the changes you did, but do you mind to add unit some tests? 

It could be something like:

```
const potentialNode :object = getSomeNode()
if (isNode(potentialNode)) {
   potentialNode.identity
}
```

Apart of this, it looks really nice.

**Comment by thebestnom** [comment]
@bigmontz added the "test" 😅
didn't find anywhere to put the other tests (no graph types) is but it shouldn't be any different and I don't think any futther tests will make any different

**Review by bigmontz — APPROVED** [review]
🌵 

Thanks for your contribution. 

Post here whenever it gets released.

**Comment by bigmontz** [comment]
Type improvement release in version 4.3.4. 

Release notes: https://github.com/neo4j/neo4j-javascript-driver/wiki/4.3-changelog#434

cc: @thebestnom

**Pull request merged**
