### PR TITLE
Expose more types to allow for external comparisons.

### PR DESCRIPTION
**Pull request by brian-gates**
```
  var exposedTypes = [
    'Node',
    'Path',
    'PathSegment',
    'Record',
    'Relationship',
    'Result',
    'ResultSummary',
    'UnboundRelationship',
  ];

  exposedTypes.forEach(type => {
    it(`should expose type ${type}`, function() {
      expect(undefined === neo4j.types[type]).toBe(false);
    });
  });
```

### CODE REVIEW

**Comment by brian-gates** [comment]
This passes for me locally

```
111 scenarios (111 passed)
386 steps (386 passed)
1m37.180s
```

**Comment by brian-gates** [comment]
Hi, is this PR being considered?

**Comment by pontusmelke** [comment]
@brian-gates Sorry for not getting back to you. I don't have time for giving this a closer look right now. However I see this PR modifies files in `lib`, these are generated files and should not be part of the PR, all changes go to files in `src`.

I'll try to take a closer look tomorrow.

**Comment by pontusmelke** [comment]
@brian-gates Looks good, but remove the files in `lib` from the PR please. Apart from that in order for me to merge you need to sign our [CLA](https://neo4j.com/developer/cla/).

**Comment by brian-gates** [comment]
Thanks @pontusmelke.

CLA sent and `lib` changes removed.

**Comment by pontusmelke** [comment]
@brian-gates sorry for the extra work, but the PR needs to be rebased. After that it should be good to go. Let me know if you have any issues with the rebase!

**Comment by brian-gates** [comment]
83affca is on top of HEAD -> 1.1 -> 3aa3479.

What would you like it rebased onto?

**Comment by pontusmelke** [comment]
@brian-gates Don't know why but github claims there were conflicts, so I merged it manually. Thanks for helping out!

**Pull request closed without merging**
