### PR TITLE
Wrap integer.d.ts with module

### PR DESCRIPTION
**Pull request by janwo**
Wrapping a module around integer to solve https://github.com/neo4j/neo4j-javascript-driver/issues/270.

### CODE REVIEW

**Comment by pocesar** [comment]
this isn't correct, since you're mixing module declaration types and the rest of the files uses exports

**Comment by lutovich** [comment]
@janwo I tried this change on your `neo4j-test` project and it does not seem to help. Am I missing something?

**Comment by janwo** [comment]
@lutovich It did work for me. Whats the error?

**Comment by lutovich** [comment]
@janwo never mind, I did not change the import. It works. I'm not entirely sure what exactly does this change mean. Maybe all declaration files should define modules like this?

@pocesar what do you think?

**Pull request closed without merging**
